spring.application.name=Resume-Parser
server:
port: 8080

spring:
main:
web-application-type: servlet

datasource:
url: jdbc:postgresql://localhost:5432/resume_parser
username: resume_parser
password: @Rajesh5630
driverClassName: org.postgresql.Driver

jpa:
ddl-auto: update
properties:
hibernate:
dialect: org.hibernate.dialect.PostgreSQLDialect
format_sql: true
show-sql: true

llm:
api:
key: your_api_key_here

docker:
compose:
enabled: false